---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dapr-system
    istio-injection: disabled
  name: dapr-system
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dapr-redis
    istio-injection: disabled
  name: dapr-redis