apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-role-binding
subjects:
- kind: ServiceAccount
  name: test-service-account
roleRef:
  kind: Role
  name: test-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-map
data:
  foo: "bar"
