apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  annotations:
    function-size: S
  name: jwt-lambda
  namespace: stage
spec:
  checksum: ""
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: jwt-lambda
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 100Mi
    status: {}
  deps: ""
  function: |-
    module.exports = { main: function (event, context) {
        return "Your JWT looks nice to me ;)"
    } }
  function-content-type: text
  handler: handler.main
  runtime: nodejs8
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: jwt-lambda
  timeout: ""
