# docker-compose -f docker-compose-local-mongo.yml up -d
# docker-compose -f docker-compose-local-mongo.yml stop

version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
