apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: personservice
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - handler: noop
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    path: /.*
  service:
    host: personservice.kyma.local
    name: personservice
    port: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: personservice
  name: personservice-internal
spec:
  hosts:
  - personservice.personservice.svc.cluster.local
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: personservice.personservice.svc.cluster.local
        port:
          number: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: personservice
     version: "1.11.0"
  annotations:
     auth.istio.io/80: NONE
  name: personservice
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: personservice
    version: "1.11.0"
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      deployment.kubernetes.io/revision: "3"
   labels:
      app: personservice
      mf_version: "2"
   name: personservice   
spec:
   replicas: 1
   selector:
      matchLabels:
         app: personservice
   template:
      metadata:
         labels:    
            app: personservice
            version: "1.11.0"
         annotations:
            sidecar.istio.io/inject: "true"
            traffic.sidecar.istio.io/includeInboundPorts: "8080"
      spec:    
         hostAliases:
# changeme: Replace with Minikube IP (command sudo minikube ip)       
          - ip: 10.181.62.254
            hostnames:
             - "gateway.kyma.local"   
             - "connector-service.kyma.local"  
         containers:
           - name: personservice
# changeme: Replace with pointer to your docker repository/container
             image: "personservice/mongokubernetes:1.11.0"
             resources:
                limits:
                   memory: 512Mi
             imagePullPolicy: Always              
             ports:
              - containerPort: 8080
                name: http
              - containerPort: 8081
                name: actuatorhttp
             env:
              - name: spring_data_mongodb_host
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_host 
              - name: spring_data_mongodb_database
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_database 
              - name: spring_data_mongodb_authentication_database
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: authentication_database 
              - name: spring_data_mongodb_password
                valueFrom: 
                   secretKeyRef:
                      name: first-mongo-mongodb
                      key: mongodb-root-password 
              - name: spring_data_mongodb_username
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_username
              - name: personservicekubernetes_swagger_host
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: service_host                          
              - name: spring_profiles_active
                value: "ApplicationConnector"  
              - name: management_health_redis_enabled
                value: "false"                     
             volumeMounts:
              - mountPath: /registration
                name: registrationfile
                readOnly: true
         volumes:
          - name: registrationfile
            configMap:
              name: registrationfile 
              items:
               - key: registrationfile.json
                 path: registrationfile.json
